server:
  port: 3000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/bms?serverTimezone=Asia/Shanghai

mybatis:
  mapper-locations: classpath:mapper/*.xml
